// Sample stories — rotates daily on the front page
window.BSK_STORIES=[
  {id:1,cat:"Politics",tone:"",img:"assets/story-politics.jpg",title:"What the New Finance Bill Means for Ordinary Sierra Leoneans",excerpt:"Parliament passed sweeping fiscal reforms this week. We break down what changes for households, small traders, and the informal sector.",author:"Admin",time:"2 hours ago",read:6},
  {id:2,cat:"Health",tone:"red",img:"assets/story-health.jpg",title:"Freetown's Hidden Health Crisis — Why Malaria Deaths Are Rising Again",excerpt:"BSK Observer visits three peripheral clinics in the Western Area where stockouts and staff shortages are quietly reversing years of progress.",author:"Admin",time:"5 hours ago",read:9},
  {id:3,cat:"Diaspora",tone:"red",img:"assets/story-diaspora.jpg",title:"Sierra Leoneans Abroad Sending Record Remittances in 2025 — But at What Cost?",excerpt:"From London to Toronto, the diaspora is sending home more than ever. Families rejoice, but economists ask what the numbers really mean.",author:"Admin",time:"8 hours ago",read:7},
  {id:4,cat:"Mining",tone:"",img:"assets/story-mining.jpg",title:"Who Is Profiting From Sierra Leone's Mineral Wealth?",excerpt:"A three-part BSK Observer investigation into revenue transparency in the iron ore and diamond sectors — six months in the making.",author:"Admin",time:"Yesterday",read:14},
  {id:5,cat:"Education",tone:"",img:"assets/story-education.jpg",title:"Koinadugu Teachers Walk 12 Miles Daily to Reach Their Students — And They Won't Stop",excerpt:"A quiet story of dedication from Sierra Leone's northeast, where the road ends and the classroom begins.",author:"Admin",time:"Yesterday",read:5},
  {id:6,cat:"Business",tone:"",img:"assets/story-business.jpg",title:"Freetown Markets Report Strongest Trading Season in Five Years",excerpt:"Vendors at Bombay Street and Big Market weigh in on what a shifting exchange rate means for the shopping basket.",author:"Admin",time:"2 days ago",read:5},
  {id:7,cat:"Culture",tone:"red",img:"assets/story-culture.jpg",title:"A New Generation Reclaims Traditional Drumming Across the Provinces",excerpt:"From Bo to Kabala, young musicians are turning heritage into a modern movement — and a livelihood.",author:"Admin",time:"2 days ago",read:6},
  {id:8,cat:"Community",tone:"",img:"assets/story-community.jpg",title:"Marampa Women's Cooperative Turns Cassava Into a Business Empire",excerpt:"A grassroots collective is quietly rewriting what economic empowerment looks like in the north.",author:"Admin",time:"3 days ago",read:7},
  {id:9,cat:"Investigations",tone:"red",img:"assets/story-politics.jpg",title:"Documents Reveal Gaps in Public Contract Disclosures",excerpt:"BSK Observer obtained six months of procurement records. What we found raises urgent questions about oversight.",author:"Admin",time:"3 days ago",read:11},
];
